# Generated by Django 3.2 on 2024-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='category',
            field=models.CharField(default='文章', max_length=50),
        ),
    ]
