# Generated by Django 3.2 on 2024-02-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='category',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='topic',
            field=models.CharField(blank=True, default='未归档', max_length=100),
        ),
    ]
