# Generated by Django 3.2 on 2024-02-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20240223_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='topic',
            field=models.CharField(choices=[('unarchived', '未归档'), ('Django开发', 'Django开发'), ('Ml', '机器学习'), ('DL', '深度学习')], default='unarchived', max_length=50),
        ),
    ]
