# Generated by Django 3.2 on 2024-02-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
